(function(b){function f(){this.regional=[];this.regional[""]={labels:"Years Months Weeks Days Hours Minutes Seconds".split(" "),labels1:"Year Month Week Day Hour Minute Second".split(" "),compactLabels:["y","m","w","d"],timeSeparator:":",isRTL:!1};this._defaults={until:null,since:null,timezone:null,serverSync:null,format:"dHMS",layout:"",compact:!1,description:"",expiryUrl:"",expiryText:"",alwaysExpire:!1,onExpiry:null,onTick:null};b.extend(this._defaults,this.regional[""])}function e(a,c){b.extend(a,
c);for(var g in c)null==c[g]&&(a[g]=null);return a}b.extend(f.prototype,{markerClassName:"hasCountdown",_timer:setInterval(function(){b.countdown._updateTargets()},980),_timerTargets:[],setDefaults:function(a){this._resetExtraLabels(this._defaults,a);e(this._defaults,a||{})},UTCDate:function(a,c,b,d,e,f,h,m){"object"==typeof c&&c.constructor==Date&&(m=c.getMilliseconds(),h=c.getSeconds(),f=c.getMinutes(),e=c.getHours(),d=c.getDate(),b=c.getMonth(),c=c.getFullYear());var k=new Date;k.setUTCFullYear(c);
k.setUTCDate(1);k.setUTCMonth(b||0);k.setUTCDate(d||1);k.setUTCHours(e||0);k.setUTCMinutes((f||0)-(30>Math.abs(a)?60*a:a));k.setUTCSeconds(h||0);k.setUTCMilliseconds(m||0);return k},_attachCountdown:function(a,c){var g=b(a);g.hasClass(this.markerClassName)||(g.addClass(this.markerClassName),g={options:b.extend({},c),_periods:[0,0,0,0,0,0,0]},b.data(a,"countdown",g),this._changeCountdown(a))},_addTarget:function(a){this._hasTarget(a)||this._timerTargets.push(a)},_hasTarget:function(a){return-1<b.inArray(a,
this._timerTargets)},_removeTarget:function(a){this._timerTargets=b.map(this._timerTargets,function(c){return c==a?null:c})},_updateTargets:function(){for(var a=0;a<this._timerTargets.length;a++)this._updateCountdown(this._timerTargets[a])},_updateCountdown:function(a,c){var g=b(a);if(c=c||b.data(a,"countdown")){g.html(this._generateHTML(c));g[(this._get(c,"isRTL")?"add":"remove")+"Class"]("countdown_rtl");(g=this._get(c,"onTick"))&&g.apply(a,["lap"!=c._hold?c._periods:this._calculatePeriods(c,c._show,
new Date)]);if("pause"!=c._hold&&(c._since?c._now.getTime()<=c._since.getTime():c._now.getTime()>=c._until.getTime())&&!c._expiring){c._expiring=!0;if(this._hasTarget(a)||this._get(c,"alwaysExpire")){this._removeTarget(a);(g=this._get(c,"onExpiry"))&&g.apply(a,[]);if(g=this._get(c,"expiryText")){var d=this._get(c,"layout");c.options.layout=g;this._updateCountdown(a,c);c.options.layout=d}if(g=this._get(c,"expiryUrl"))window.location=g}c._expiring=!1}else"pause"==c._hold&&this._removeTarget(a);b.data(a,
"countdown",c)}},_changeCountdown:function(a,c,g){c=c||{};if("string"==typeof c){var d=c;c={};c[d]=g}if(g=b.data(a,"countdown"))this._resetExtraLabels(g.options,c),e(g.options,c),this._adjustSettings(a,g),b.data(a,"countdown",g),c=new Date,(g._since&&g._since<c||g._until&&g._until>c)&&this._addTarget(a),this._updateCountdown(a,g)},_resetExtraLabels:function(a,c){var b=!1,d;for(d in c)if(d.match(/[Ll]abels/)){b=!0;break}if(b)for(d in a)d.match(/[Ll]abels[0-9]/)&&(a[d]=null)},_adjustSettings:function(a,
c){var b=this._get(c,"serverSync"),b=b?b.apply(a,[]):null,d=new Date,e=this._get(c,"timezone"),e=null==e?-d.getTimezoneOffset():e;c._since=this._get(c,"since");c._since&&(c._since=this.UTCDate(e,this._determineTime(c._since,null)),c._since&&b&&c._since.setMilliseconds(c._since.getMilliseconds()+d.getTime()-b.getTime()));c._until=this.UTCDate(e,this._determineTime(this._get(c,"until"),d));b&&c._until.setMilliseconds(c._until.getMilliseconds()+d.getTime()-b.getTime());c._show=this._determineShow(c)},
_destroyCountdown:function(a){var c=b(a);c.hasClass(this.markerClassName)&&(this._removeTarget(a),c.removeClass(this.markerClassName).empty(),b.removeData(a,"countdown"))},_pauseCountdown:function(a){this._hold(a,"pause")},_lapCountdown:function(a){this._hold(a,"lap")},_resumeCountdown:function(a){this._hold(a,null)},_hold:function(a,c){var g=b.data(a,"countdown");if(g){if("pause"==g._hold&&!c){g._periods=g._savePeriods;var d=g._since?"-":"+";g[g._since?"_since":"_until"]=this._determineTime(d+g._periods[0]+
"y"+d+g._periods[1]+"o"+d+g._periods[2]+"w"+d+g._periods[3]+"d"+d+g._periods[4]+"h"+d+g._periods[5]+"m"+d+g._periods[6]+"s");this._addTarget(a)}g._hold=c;g._savePeriods="pause"==c?g._periods:null;b.data(a,"countdown",g);this._updateCountdown(a,g)}},_getTimesCountdown:function(a){return(a=b.data(a,"countdown"))?a._hold?this._calculatePeriods(a,a._show,new Date):a._periods:null},_get:function(a,c){return null!=a.options[c]?a.options[c]:b.countdown._defaults[c]},_determineTime:function(a,c){var g=function(a){var b=
new Date;b.setTime(b.getTime()+1E3*a);return b},d=function(a){a=a.toLowerCase();for(var c=new Date,d=c.getFullYear(),g=c.getMonth(),e=c.getDate(),f=c.getHours(),p=c.getMinutes(),c=c.getSeconds(),n=/([+-]?[0-9]+)\s*(s|m|h|d|w|o|y)?/g,l=n.exec(a);l;){switch(l[2]||"s"){case "s":c+=parseInt(l[1],10);break;case "m":p+=parseInt(l[1],10);break;case "h":f+=parseInt(l[1],10);break;case "d":e+=parseInt(l[1],10);break;case "w":e+=7*parseInt(l[1],10);break;case "o":g+=parseInt(l[1],10);e=Math.min(e,b.countdown._getDaysInMonth(d,
g));break;case "y":d+=parseInt(l[1],10),e=Math.min(e,b.countdown._getDaysInMonth(d,g))}l=n.exec(a)}return new Date(d,g,e,f,p,c,0)};(g=null==a?c:"string"==typeof a?d(a):"number"==typeof a?g(a):a)&&g.setMilliseconds(0);return g},_getDaysInMonth:function(a,c){return 32-(new Date(a,c,32)).getDate()},_generateHTML:function(a){a._periods=periods=a._hold?a._periods:this._calculatePeriods(a,a._show,new Date);for(var c=!1,g=0,d=0;d<a._show.length;d++)c|="?"==a._show[d]&&0<periods[d],a._show[d]="?"!=a._show[d]||
c?a._show[d]:null,g+=a._show[d]?1:0;var c=this._get(a,"compact"),d=this._get(a,"layout"),e=c?this._get(a,"compactLabels"):this._get(a,"labels"),f=this._get(a,"timeSeparator"),h=this._get(a,"description")||"",m=function(c){var d=b.countdown._get(a,"compactLabels"+periods[c]);return a._show[c]?periods[c]+(d?d[c]:e[c])+" ":""},k=function(c){var d=b.countdown._get(a,"labels"+periods[c]);return a._show[c]?'<span class="countdown_section"><span class="countdown_amount">'+periods[c]+"</span><br/>"+(d?d[c]:
e[c])+"</span>":""};return d?this._buildLayout(a,d,c):(c?'<span class="countdown_row countdown_amount'+(a._hold?" countdown_holding":"")+'">'+m(0)+m(1)+m(2)+m(3)+(a._show[4]?this._minDigits(periods[4],2):"")+(a._show[5]?(a._show[4]?f:"")+this._minDigits(periods[5],2):"")+(a._show[6]?(a._show[4]||a._show[5]?f:"")+this._minDigits(periods[6],2):""):'<span class="countdown_row countdown_show'+g+(a._hold?" countdown_holding":"")+'">'+k(0)+k(1)+k(2)+k(3)+k(4)+k(5)+k(6))+"</span>"+(h?'<span class="countdown_row countdown_descr">'+
h+"</span>":"")},_buildLayout:function(a,c,g){var d=this._get(a,g?"compactLabels":"labels"),e=function(c){return(b.countdown._get(a,(g?"compactLabels":"labels")+a._periods[c])||d)[c]},f=function(a,c){return Math.floor(a/c)%10},e={desc:this._get(a,"description"),sep:this._get(a,"timeSeparator"),yl:e(0),yn:a._periods[0],ynn:this._minDigits(a._periods[0],2),ynnn:this._minDigits(a._periods[0],3),y1:f(a._periods[0],1),y10:f(a._periods[0],10),y100:f(a._periods[0],100),ol:e(1),on:a._periods[1],onn:this._minDigits(a._periods[1],
2),onnn:this._minDigits(a._periods[1],3),o1:f(a._periods[1],1),o10:f(a._periods[1],10),o100:f(a._periods[1],100),wl:e(2),wn:a._periods[2],wnn:this._minDigits(a._periods[2],2),wnnn:this._minDigits(a._periods[2],3),w1:f(a._periods[2],1),w10:f(a._periods[2],10),w100:f(a._periods[2],100),dl:e(3),dn:a._periods[3],dnn:this._minDigits(a._periods[3],2),dnnn:this._minDigits(a._periods[3],3),d1:f(a._periods[3],1),d10:f(a._periods[3],10),d100:f(a._periods[3],100),hl:e(4),hn:a._periods[4],hnn:this._minDigits(a._periods[4],
2),hnnn:this._minDigits(a._periods[4],3),h1:f(a._periods[4],1),h10:f(a._periods[4],10),h100:f(a._periods[4],100),ml:e(5),mn:a._periods[5],mnn:this._minDigits(a._periods[5],2),mnnn:this._minDigits(a._periods[5],3),m1:f(a._periods[5],1),m10:f(a._periods[5],10),m100:f(a._periods[5],100),sl:e(6),sn:a._periods[6],snn:this._minDigits(a._periods[6],2),snnn:this._minDigits(a._periods[6],3),s1:f(a._periods[6],1),s10:f(a._periods[6],10),s100:f(a._periods[6],100)},h=c;for(c=0;7>c;c++)f="yowdhms".charAt(c),h=
h.replace(new RegExp("\\{"+f+"<\\}(.*)\\{"+f+">\\}","g"),a._show[c]?"$1":"");b.each(e,function(a,c){h=h.replace(new RegExp("\\{"+a+"\\}","g"),c)});return h},_minDigits:function(a,c){a="0000000000"+a;return a.substr(a.length-c)},_determineShow:function(a){a=this._get(a,"format");var c=[];c[0]=a.match("y")?"?":a.match("Y")?"!":null;c[1]=a.match("o")?"?":a.match("O")?"!":null;c[2]=a.match("w")?"?":a.match("W")?"!":null;c[3]=a.match("d")?"?":a.match("D")?"!":null;c[4]=a.match("h")?"?":a.match("H")?"!":
null;c[5]=a.match("m")?"?":a.match("M")?"!":null;c[6]=a.match("s")?"?":a.match("S")?"!":null;return c},_calculatePeriods:function(a,c,g){a._now=g;a._now.setMilliseconds(0);var d=new Date(a._now.getTime());a._since&&g.getTime()<a._since.getTime()?a._now=g=d:a._since?g=a._since:(d.setTime(a._until.getTime()),g.getTime()>a._until.getTime()&&(a._now=g=d));var e=[0,0,0,0,0,0,0];if(c[0]||c[1]){var f=b.countdown._getDaysInMonth(g.getFullYear(),g.getMonth()),h=b.countdown._getDaysInMonth(d.getFullYear(),
d.getMonth()),m=d.getDate()==g.getDate()||d.getDate()>=Math.min(f,h)&&g.getDate()>=Math.min(f,h),k=function(a){return 60*(60*a.getHours()+a.getMinutes())+a.getSeconds()},m=Math.max(0,12*(d.getFullYear()-g.getFullYear())+d.getMonth()-g.getMonth()+(d.getDate()<g.getDate()&&!m||m&&k(d)<k(g)?-1:0));e[0]=c[0]?Math.floor(m/12):0;e[1]=c[1]?m-12*e[0]:0;m=function(a,c,d){d=a.getDate()==d;var g=b.countdown._getDaysInMonth(a.getFullYear()+c*e[0],a.getMonth()+c*e[1]);a.getDate()>g&&a.setDate(g);a.setFullYear(a.getFullYear()+
c*e[0]);a.setMonth(a.getMonth()+c*e[1]);d&&a.setDate(g);return a};a._since?d=m(d,-1,h):g=m(new Date(g.getTime()),1,f)}var v=Math.floor((d.getTime()-g.getTime())/1E3);a=function(a,b){e[a]=c[a]?Math.floor(v/b):0;v-=e[a]*b};a(2,604800);a(3,86400);a(4,3600);a(5,60);a(6,1);return e}});b.fn.countdown=function(a){var c=Array.prototype.slice.call(arguments,1);return"getTimes"==a?b.countdown["_"+a+"Countdown"].apply(b.countdown,[this[0]].concat(c)):this.each(function(){"string"==typeof a?b.countdown["_"+a+
"Countdown"].apply(b.countdown,[this].concat(c)):b.countdown._attachCountdown(this,a)})};b.countdown=new f})(jQuery);if("undefined"==typeof SEARCH_URL)var SEARCH_URL="http://so.eelly.com";
var elyHd={searchDomain:SEARCH_URL,set_search_kw:{goods_kw:"",store_kw:""},openType:"_blank",$searchInput:null,$searchBtn:null,$searchType:null,init:function(){this.$searchInput=$("#s_keyword");this.$searchBtn=$("#ely-hd").find(".submit-btn");this.$searchType=$("#js_search_type");this._setHotKey();this._eventBind();$("#ely-hd").trigger("initComplete")},_setHotKey:function(){var b=this;if(b.set_search_kw.goods_kw)b._setSearchKw();else{var f=SEARCH_URL.replace(/(http:|https:)\/\//,"//");$.getJSON(f+
"/index.php?app=default&act=getSearchWord&jsoncallback=?",function(e){e.flag&&(b.set_search_kw.goods_kw=e.goods_kw,b.set_search_kw.store_kw=e.store_kw,b._setSearchKw());$("#ely-hd").trigger("hotKeyComplete")})}},searchGo:function(b,f,e,a){var c=this.$searchInput;f=f||this.openType;void 0==b&&(b=this.$searchType.find(".J_current-type").attr("data-searchapp"));e=e||c.val();e=$.trim(e);if(/[\[,\],\&,\#]/.test(e))return alert("\u641c\u7d22\u65f6\u8bf7\u4e0d\u8981\u8f93\u5165\u975e\u6cd5\u5b57\u7b26\uff0c\u5982\uff1a[,],&,#"),
!1;if(""==e||e==this.set_search_kw.goods_kw||e==this.set_search_kw.store_kw)switch(b){case "searchgoods":location.href=SEARCH_LIST_URL;break;case "searchstore":location.href=SEARCH_LIST_URL+"/s-act-store.html"}else{if("\u8863\u8054\u901a"==e)return window.open(SITE_URL+"/index.php?app=im1"),!1;a=this.searchUrlFn(e,b,a);if("searchgoods"==b){var g=$.getCookie("keyword"),c=e;""!=g&&null!=g&&(c=e+","+g);var g=location.host.split("."),d=g.length;$.setCookie("keyword",c,null,null,g[d-2]+"."+g[d-1])}e&&
"searchgoods"==b&&(b={},b.keyword=e,_eaq.push(["trackClickEvent","logUserSearch",b]));switch(f){case "_self":location.href=a;break;default:window.open(a)}return!0}},searchUrlFn:function(b,f,e){e=e||"";var a=this.searchDomain;0<b.indexOf("(")&&(b=b.replace(/\(/,"%28"));0<b.indexOf(")")&&(b=b.replace(/\)/,"%29"));return a+"/index.php?app="+f+"&act=search&keyword="+encodeURI(b)+e},_eventBind:function(){var b=this,f=b.set_search_kw,e=b.$searchInput,a=b.$searchType;e.focus(function(){$(this).removeClass("search-set");
var a=$(this).val();a!=f.goods_kw&&a!=f.store_kw||$(this).val("")}).blur(function(){b._setSearchKw()});e.keypress(function(a){13==a.which&&(a.preventDefault(),b.searchGo())});b.$searchBtn.click(function(){b.searchGo()});a.find("li").hover(function(){var c=$(this);a.css("overflow","visible");c.siblings("li").show()},function(){$(this);a.css("overflow","hidden")}).click(function(){var a=$(this),g=a.siblings(),d=a.attr("data-searchapp"),e=a.find("a").text(),f=g.attr("data-searchapp"),h=g.find("a").text();
a.attr("data-searchapp",f).find("a").text(h);g.attr("data-searchapp",d).find("a").text(e);b._setSearchKw()})},_setSearchKw:function(){var b=this.$searchType.find(".J_current-type").attr("data-searchapp"),f=this.set_search_kw,e=f.goods_kw,a=this.$searchInput,c=a.val();"searchstore"==b&&(e=f.store_kw);""==c?(a.val(e),a.addClass("search-set")):$.each(f,function(b,d){c==d&&a.val(e)})}};$(function(){elyHd.init()});
$(function(){function b(){var a=$("#J_fb_input").val().length;g=$("#J_fb_input").val();d=$("#J_fb_type").val();g=g.replace(/(^\s*)/g,"");500<a&&(a=500,$("#J_fb_input").val(g.substr(0,500)));$("#J_fb_last").html(a+"/500");c=0<a&&500>=a&&""!=g&&"\u60a8\u7559\u4e0b\u7684\u6bcf\u4e00\u4e2a\u5efa\u8bae\u90fd\u662f\u6211\u4eec\u4e0d\u65ad\u6539\u8fdb\u7684\u52a8\u529b\uff01"!=g?!0:!1}function f(){"admin"==$("#is_admin").html()?($("#J_feedback_box").attr("class","sl-fixed sl-fixed-right sl-fixed-top feedback-box feedback-box-showing").find("#J_fb_form").stop().show(100),
$("#J_feedback_box").css("z-index",1E3)):($("#J_feedback_box").attr("class","sl-fixed sl-fixed-right sl-fixed-top feedback-box feedback-box-showing").find("#J_fb_form").stop().animate({right:0},300),0<$(".index").length?$("#J_fb_default").css("background-position","-30px -44px").mouseout(function(){$(this).css("background-position","-30px -44px")}):$("#J_fb_default").hide())}function e(){$("#J_fb_tips").hide();"admin"==$("#is_admin").html()?($("#J_feedback_box").find("#J_fb_form").stop().hide(200,
function(){$("#J_feedback_box").attr("class","sl-fixed sl-fixed-right sl-fixed-top feedback-box feedback-box-hiding")}),$("#J_feedback_box").css("z-index",90)):$("#J_feedback_box").find("#J_fb_form").stop().animate({right:0},150,function(){$("#J_feedback_box").attr("class","sl-fixed sl-fixed-right sl-fixed-top feedback-box feedback-box-hiding")});$("#J_fb_default").show();0<$(".index").length&&$("#J_fb_default").css("background-position","0 -44px").mouseover(function(){$(this).css("background-position",
"-30px -44px")}).mouseout(function(){$(this).css("background-position","0 -44px")});$("#J_fb_input").css("color","#999").val("\u60a8\u7559\u4e0b\u7684\u6bcf\u4e00\u4e2a\u5efa\u8bae\u90fd\u662f\u6211\u4eec\u4e0d\u65ad\u6539\u8fdb\u7684\u52a8\u529b\uff01")}function a(){b();1==c?$.post("./index.php?app=default&act=feedback",{content:g,from_page:document.location.href,type:d},function(a){if(a)return-1==a?$("#J_fb_tips .content").html('<p class="fb-tips-success"><span class="fb-sprite fb-icon-success"></span>\u8bf7\u95f4\u969410\u79d2\u63d0\u4ea4\u5efa\u8bae!\u611f\u8c22!</p>'):
$("#J_fb_tips .content").html('<p class="fb-tips-success"><span class="fb-sprite fb-icon-success"></span>\u63d0\u4ea4\u6210\u529f\uff0c\u611f\u8c22\u60a8\u5bf9\u8863\u8054\u7684\u652f\u6301\uff01</p>'),$("#J_fb_last").html("0/500"),$("#J_fb_input").val(""),!1}):0==c&&($("#J_fb_tips .content").html('<p class="fb-tips-error"><span class="fb-sprite fb-icon-error"></span>\u63d0\u4ea4\u524d\u5148\u7ed9\u70b9\u5efa\u8bae\u5427\uff01</p>'),$("#J_fb_last").html("0/500"),$("#J_fb_input").val(""));$("#J_fb_tips").show()}
var c=!0,g="",d=1;$("#J_fb_input").focus(function(){"\u60a8\u7559\u4e0b\u7684\u6bcf\u4e00\u4e2a\u5efa\u8bae\u90fd\u662f\u6211\u4eec\u4e0d\u65ad\u6539\u8fdb\u7684\u52a8\u529b\uff01"==$(this).val()&&$(this).css("color","#444").val("")}).blur(function(){""==$(this).val()&&$(this).css("color","#999").val("\u60a8\u7559\u4e0b\u7684\u6bcf\u4e00\u4e2a\u5efa\u8bae\u90fd\u662f\u6211\u4eec\u4e0d\u65ad\u6539\u8fdb\u7684\u52a8\u529b\uff01")});$.browser.msie&&7>$.browser.version&&$("#J_fb_default").mouseover(function(){$(this).addClass("fb-default-hover")}).mouseout(function(){$(this).removeClass("fb-default-hover")});
$("#J_fb_default").bind("click",function(){"admin"==$("#is_admin").html()||0<$(".index").length?$("#J_fb_form").is(":hidden")?f():e():f()});$("#J_fb_close").bind("click",function(){e()});$("#J_fb_submit").bind("click",function(){a();$("#J_fb_tips").bind("click",function(){c?e():$("#J_fb_tips").hide();clearTimeout(b)});var b=setTimeout(function(){$("#J_fb_tips").click()},1800)});$("#J_fb_input").bind("keyup",function(){b()})});
function show_dialog_satisfaction(b,f,e,a){b=isNaN(b)?0:b;setTimeout(function(){$.get("index.php?app=satisfaction",{user_type:f?f:"1",reload:e?1:0,score:a?a:0},function(a){art.dialog({resize:!1,id:"dialog_satisfaction",title:"\u540e\u53f0\u7528\u6237\u6ee1\u610f\u5ea6\u8c03\u67e5"}).content(a);var b=$("#score").val();a=b||0;for(var d=0;d<$(".mg-survey .p-star span").length;d++)3<a?$(".mg-survey .p-star span")[d].className=d<a?"on":"":$(".mg-survey .p-star span")[d].className=d<a?"of":"";3<=b?($(".sug-text").val("\u6b22\u8fce\u60a8\u7559\u4e0b\u66f4\u591a\u5efa\u8bae\uff0c\u6211\u4eec\u4f1a\u6301\u7eed\u6539\u8fdb\u54e6\uff01"),
$(".sug-text").attr("defaultValue","\u6b22\u8fce\u60a8\u7559\u4e0b\u66f4\u591a\u5efa\u8bae\uff0c\u6211\u4eec\u4f1a\u6301\u7eed\u6539\u8fdb\u54e6\uff01")):($(".sug-text").val("\u8bf7\u7559\u4e0b\u60a8\u7684\u610f\u89c1\uff0c\u6211\u4eec\u7684\u8fdb\u6b65\u9700\u8981\u60a8\u7684\u53c2\u4e0e\uff01"),$(".sug-text").attr("defaultValue","\u8bf7\u7559\u4e0b\u60a8\u7684\u610f\u89c1\uff0c\u6211\u4eec\u7684\u8fdb\u6b65\u9700\u8981\u60a8\u7684\u53c2\u4e0e\uff01"));$(".star-txt").html(["1\u5206 \u592a\u70c2\u4e86",
"2\u5206 \u5f88\u4e0d\u6ee1\u610f","3\u5206 \u4e0d\u662f\u5f88\u597d","4\u5206 \u4e00\u822c","5\u5206 \u5f88\u6ee1\u610f"][b-1])},"html")},b)}
(function(b){function f(a,g){return parseInt(b.css(a[0],g))||0}function e(a){return a[0].offsetWidth+f(a,"marginLeft")+f(a,"marginRight")}function a(a){return a[0].offsetHeight+f(a,"marginTop")+f(a,"marginBottom")}b.fn.jCarouselLite=function(c){c=b.extend({btnPrev:null,btnNext:null,btnGo:null,mouseWheel:!1,auto:null,speed:200,easing:null,vertical:!1,circular:!0,visible:3,start:0,scroll:1,beforeStart:null,afterEnd:null,mousehover:!1},c||{});return this.each(function(){function g(a){if(!d){c.beforeStart&&
c.beforeStart.call(this,n.slice(r).slice(0,p));if(c.circular)a<=c.start-p-1?(m.css(f,-((l-2*p)*s)+"px"),r=a==c.start-p-1?l-2*p-1:l-2*p-c.scroll):a>=l-p+1?(m.css(f,-(p*s)+"px"),r=a==l-p+1?p+1:p+c.scroll):r=a;else{if(0>a||a>l-p)return;r=a}d=!0;m.animate("left"==f?{left:-(r*s)}:{top:-(r*s)},c.speed,c.easing,function(){c.afterEnd&&c.afterEnd.call(this,n.slice(r).slice(0,p));d=!1});c.circular||(b(c.btnPrev+","+c.btnNext).removeClass("disabled"),b(0>r-c.scroll&&c.btnPrev||r+c.scroll>l-p&&c.btnNext||[]).addClass("disabled"))}return!1}
var d=!1,f=c.vertical?"top":"left",q=c.vertical?"height":"width",h=b(this),m=b("ul",h),k=b("li",m),v=k.size(),p=c.visible;c.circular&&(m.prepend(k.slice(v-p-1+1).clone()).append(k.slice(0,p).clone()),c.start+=p);var n=b("li",m),l=n.size(),r=c.start;h.css("visibility","visible");n.css({overflow:"hidden","float":c.vertical?"none":"left"});m.css({margin:"0",padding:"0",position:"relative","list-style-type":"none","z-index":"1"});h.css({overflow:"hidden",position:"relative","z-index":"2",left:"0px"});
var s=c.vertical?a(n):e(n),k=s*l,v=s*p;n.css({width:n.width(),height:n.height()});m.css(q,k+"px").css(f,-(r*s));h.css(q,v+"px");c.btnPrev&&b(c.btnPrev).click(function(){return g(r-c.scroll)});c.btnNext&&b(c.btnNext).click(function(){return g(r+c.scroll)});c.btnGo&&b.each(c.btnGo,function(a,d){b(d).click(function(){return g(c.circular?c.visible+a:a)})});c.mouseWheel&&h.mousewheel&&h.mousewheel(function(a,b){return 0<b?g(r-c.scroll):g(r+c.scroll)});if(c.auto){var w=setInterval(function(){g(r+c.scroll)},
c.auto+c.speed);c.mousehover&&h.hover(function(){clearInterval(w)},function(){w=setInterval(function(){g(r+c.scroll)},c.auto+c.speed)})}})}})(jQuery);var online=[],urlroot="http://im.bizapp.qq.com:8000/",tOut=-1,drag=!1,g_safeNode=null;lastScrollY=0;var kfguin,ws,companyname,welcomeword,type,wpadomain,eid,Browser={ie:/msie/.test(window.navigator.userAgent.toLowerCase()),moz:/gecko/.test(window.navigator.userAgent.toLowerCase()),opera:/opera/.test(window.navigator.userAgent.toLowerCase()),safari:/safari/.test(window.navigator.userAgent.toLowerCase())};
kfguin&&(_Ten_rightDivHtml='<div id="_Ten_rightDiv" style="position:absolute; top:160px; right:1px; display:none;">',_Ten_rightDivHtml+=kf_getPopup_Ten_rightDivHtml(kfguin,ws,wpadomain),_Ten_rightDivHtml+="</div>",document.write(_Ten_rightDivHtml),1==type&&0==kf_getCookie("hasshown")&&(companyname=companyname.substr(0,15),welcomeword=kf_processWelcomeword(welcomeword),kfguin=kf_getSafeHTML(kfguin),companyname=kf_getSafeHTML(companyname),welcomeword=welcomeword.replace(/<brT>/g,"\r\n"),welcomeword=
kf_getSafeHTML(welcomeword),welcomeword=welcomeword.replace(/\r/g,"").replace(/\n/g,"<BR>"),window.setTimeout("kf_sleepShow()",1E4)),window.setTimeout("kf_moveWithScroll()",1));function kf_getSafeHTML(b){var f="",e=g_safeNode;e||(e=document.createElement("TEXTAREA"));e&&(Browser.moz?e.textContent=b:e.innerText=b,f=e.innerHTML,Browser.moz?e.textContent="":e.innerText="",g_safeNode=e);return f}
function kf_moveWithScroll(){"undefined"!=typeof window.pageYOffset?nowY=window.pageYOffset:"undefined"!=typeof document.compatMode&&"BackCompat"!=document.compatMode?nowY=document.documentElement.scrollTop:"undefined"!=typeof document.body&&(nowY=document.body.scrollTop);percent=.1*(nowY-lastScrollY);percent=0<percent?Math.ceil(percent):Math.floor(percent);document.getElementById("_Ten_rightDiv").style.top=parseInt(document.getElementById("_Ten_rightDiv").style.top)+percent+"px";document.getElementById("kfpopupDiv")&&
(document.getElementById("kfpopupDiv").style.top=parseInt(document.getElementById("kfpopupDiv").style.top)+percent+"px");lastScrollY+=percent;tOut=window.setTimeout("kf_moveWithScroll()",1)}function kf_hide(){-1!=tOut&&(clearTimeout(tOut),tOut=-1);void 0!=document.getElementById("_Ten_rightDiv")&&(document.getElementById("_Ten_rightDiv").style.visibility="hidden",document.getElementById("_Ten_rightDiv").style.display="none")}
function kf_hidekfpopup(){-1!=tOut&&(clearTimeout(tOut),tOut=-1);document.getElementById("kfpopupDiv").style.visibility="hidden";document.getElementById("kfpopupDiv").style.display="none";tOut=window.setTimeout("kf_moveWithScroll()",1)}
function kf_getPopupDivHtml(b,f,e,a,c){f=""+('<div style="float:left; height:150px; width:8px; background-image:url('+urlroot+'bg_1.gif);"></div>');f+='<div style="font-family:Tahoma; text-align:left; float:left; height:150px; width:324px; background-image:url('+urlroot+'bg_2.gif); background-repeat:repeat-x;">';f+='<div><h1 style="float:left; width:250px; height:28px; line-height:28px; padding:2px 20px 0 2px; margin:0 0 9px 0; font-size:14px; color:#FFFFFF; display:block; background:none; border:none; position:static;">'+
e+'</h1><a href="#" onclick="kf_hidekfpopup();return false;" style="background-image: url('+urlroot+'close.gif); float:right; height:19px; width:42px;" onmouseover="javascript:this.style.backgroundPosition=\'bottom\'" onmouseout="javascript:this.style.backgroundPosition=\'top\'"></a></div>';f=f+'<div style="height:83px; padding:0 0 0 2px; clear:both;">'+('<div style="background-image:url('+urlroot+'face.jpg); height:70px; width:70px; float:left;"></div>');f=f+('<p style="font-family:Tahoma; font-size:12px; line-height:24px; width: 240px; margin:0px; padding: 0 0 0 12px; display:block; float:left; margin-top:2px; word-wrap:break-word;">'+
a+"</p></div>")+'<div style="clear:both;">';f+='<a onclick="kf_hidekfpopup();return false;" href="#" style="float:right; background-image:url('+urlroot+'btn_1.gif); margin:0 0 0 5px; padding:0px; border:0px; height:21px; width:69px;"></a>';f+="<a onclick=\"kf_openChatWindow(1,'"+c+"','"+b+'\')" href="#" style="float:right; background-image:url('+urlroot+'btn_2.gif); margin:0; padding:0px; border:0px; height:21px; width:69px;"></a></div>';return f+('</div><div style="float:left; height:150px; width:8px; background-image:url('+
urlroot+'bg_1.gif); background-position:right;"></div>')}
function kf_getPopup_Ten_rightDivHtml(b,f,e){f='<div style="width:35px; height:302px;"><img src="http://www.eelly.com/themes/mall/default/styles/default/images/custom_icon.jpg" width="35" height="302" border="0" usemap="#Map" /><map name="Map" id="Map">'+('<area shape="rect" coords="3,5,32,99" href="javascript:;" onclick="kf_openChatWindow(0,\''+e+"','"+b+'\')" title="\u7f51\u7ad9\u5e2e\u52a9" />');f+='<area shape="rect" coords="4,102,32,204" href="http://bbs.eelly.com/forum.php" target="_blank" title="\u5e97\u4e3b\u4ea4\u6d41" />';f+=
'<area shape="rect" coords="3,208,33,299" href="javascript:;" onclick="this.style.behavior=\'url(#default#homepage)\';this.setHomePage(\'http://www.eelly.com/\');return(false);" style="behavior: url(#default#homepage)" />';return f+"</map></div>"}function kf_openChatWindow(b,f,e){window.open("http://wpa.b.qq.com/cgi/wpa.php?ln=1&key=XzgwMDAzNzAzNV80NDA0N184MDAwMzcwMzVfMl8","_blank","height=544, width=644,toolbar=no,scrollbars=no,menubar=no,status=no");return!1}
function kf_validateWelcomeword(b){for(var f=0,e=0;e<b.length;e++)if("\n"==b.charAt(e)&&f++,2<f)return 2;if(b.length>57+2*f)return 1;f=0;for(e=b.indexOf("\n");-1!=e;)b=b.substr(e+1),19>=e-1?f+=19:38>=e-1?f+=38:57>=e-1&&(f+=57),e=b.indexOf("\n");f+=b.length;return 57<f?3:0}
function kf_processWelcomeword(b){b=b.substr(0,67);for(var f="",e=0,a=b.indexOf("<brT>");57>e&&-1!=a;)19>=a?(e+=19,f=57>=e?f+b.substr(0,a+5):f+b.substr(0,57-e>b.length?b.length:57-e)):38>=a?(e+=38,f=57>=e?f+b.substr(0,a+5):f+b.substr(0,57-e>b.length?b.length:57-e)):57>=a&&(e+=57,f=57>=e?f+b.substr(0,a+5):f+b.substr(0,57-e>b.length?b.length:57-e)),b=b.substr(a+5),a=b.indexOf("<brT>");57>e&&(f+=b.substr(0,57-e>b.length?b.length:57-e));return f}
function kf_setCookie(b,f,e,a,c){b=b+"="+escape(f)+";";f=null;"object"==typeof e?f=e:"number"==typeof e&&(f=new Date,f=new Date(f.getFullYear(),f.getMonth(),f.getDate(),f.getHours(),f.getMinutes()+e,f.getSeconds(),f.getMilliseconds()));f&&(b+="expires="+f.toGMTString()+";");a?"string"==typeof a&&""!=a&&(b+="path="+a+";"):b+="path=/;";c||"undefined"==typeof VS_COOKIEDM||(c=VS_COOKIEDM);"string"==typeof c&&""!=c&&(b+="domain="+c+";");document.cookie=b}
function kf_getCookie(b){var f="",e=document.cookie.split("; "),a,c;for(c=0;c<e.length;c++)(a=e[c].split("="))&&2<=a.length&&b==kf_rTrim(kf_lTrim(a[0]))&&(f=unescape(a[1]));return f}
function kf_sleepShow(){kf_setCookie("hasshown",1,"","/",wpadomain+".qq.com");popupDivHtml='<div id="kfpopupDiv" onmousedown="MyMove.Move(\'kfpopupDiv\',event,1);"  style="z-index:10000;filter:alpha(opacity=90);position: absolute; top: '+(parseInt(document.getElementById("_Ten_rightDiv").style.top)+170)+'px; right: 500px;color:#000;font-size: 12px;cursor:move;height: 150px;width: 340px;">';popupDivHtml+=kf_getPopupDivHtml(kfguin,ws,companyname,welcomeword,wpadomain);popupDivHtml+="</div>";document.body.insertAdjacentHTML("beforeEnd",
popupDivHtml)}function kf_dealErrors(){kf_hide();return!0}function kf_lTrim(b){for(;" "==b.charAt(0);)b=b.slice(1);return b}function kf_rTrim(b){for(var f=b.length;" "==b.charAt(f-1);)b=b.slice(0,f-1),f--;return b}window.onerror=kf_dealErrors;var MyMove=new Tong_MoveDiv;
function Tong_MoveDiv(){this.Move=function(b,f,e){if(""!=b){var a=document.getElementById(b);if(a){evt=f?f:window.event;a.style.position="absolute";a.style.zIndex=9999;f=a.offsetWidth;var c=a.offsetHeight,g=a.offsetLeft,a=a.offsetTop,d=document.createElement("DIV");document.body.appendChild(d);d.style.cssText="filter:alpha(Opacity=10,style=0);opacity:0.2;width:"+f+"px;height:"+c+"px;top:"+a+"px;left:"+g+"px;position:absolute;background:#000";d.setAttribute("id",b+"temp");this.Move_OnlyMove(b,evt,
e)}}};this.Move_OnlyMove=function(b,f,e){var a=document.getElementById(b+"temp");if(a){evt=f?f:window.event;var c=evt.clientX-a.offsetLeft,g=evt.clientY-a.offsetTop;window.captureEvents?window.captureEvents(Event.MOUSEMOVE|Event.MOUSEUP):a.setCapture();document.onmousemove=function(b){if(a){b=b?b:window.event;var e=Math.max(document.body.scrollHeight,document.body.clientHeight,document.body.offsetHeight,document.documentElement.scrollHeight,document.documentElement.clientHeight,document.documentElement.offsetHeight),
f=Math.max(document.body.scrollWidth,document.body.clientWidth,document.body.offsetWidth,document.documentElement.scrollWidth,document.documentElement.clientWidth,document.documentElement.offsetWidth),h=0;document.body.scrollWidth<f&&(h=document.body.scrollWidth);document.body.clientWidth<f&&h<document.body.clientWidth&&(h=document.body.clientWidth);document.body.offsetWidth<f&&h<document.body.offsetWidth&&(h=document.body.offsetWidth);document.documentElement.scrollWidth<f&&h<document.documentElement.scrollWidth&&
(h=document.documentElement.scrollWidth);document.documentElement.clientWidth<f&&h<document.documentElement.clientWidth&&(h=document.documentElement.clientWidth);document.documentElement.offsetWidth<f&&h<document.documentElement.offsetWidth&&(h=document.documentElement.offsetWidth);a.style.left=0>=b.clientX-c?"0px":b.clientX-c>=f-a.offsetWidth-2?h-a.offsetWidth-2+"px":b.clientX-c+"px";a.style.top=1>=b.clientY-g?"1px":b.clientY-g>=e-a.offsetHeight-30?e-a.offsetHeight+"px":b.clientY-g+"px"}};document.onmouseup=
function(){if(a){window.captureEvents?window.releaseEvents(Event.MOUSEMOVE|Event.MOUSEUP):a.releaseCapture();var c=document.getElementById(b);c&&(MyMove.Move_e(b,a.offsetLeft,a.offsetTop,c.offsetLeft,c.offsetTop,e),document.body.removeChild(a),a=null)}}}};this.Move_e=function(b,f,e,a,c,g){"undefined"!=typeof window["ct"+b]&&clearTimeout(window["ct"+b]);var d=document.getElementById(b);if(d){var u=st=8,q=Math.abs(f-a),h=Math.abs(e-c);0<q-h?u=h?8<Math.round(q/h)?8:6*Math.round(q/h):0:st=q?8<Math.round(h/
q)?8:6*Math.round(h/q):0;0>f-a&&(u*=-1);0>e-c&&(st*=-1);52>Math.abs(a+u-f)&&u&&(u=0<u?2:-2);52>Math.abs(c+st-e)&&st&&(st=0<st?2:-2);16>Math.abs(a+u-f)&&u&&(u=0<u?1:-1);16>Math.abs(c+st-e)&&st&&(st=0<st?1:-1);if(0!=q||0!=h)g?(d.style.left=f+"px",d.style.top=e+"px"):(2>Math.abs(a+u-f)?d.style.left=f+"px":d.style.left=a+u+"px",2>Math.abs(c+st-e)?d.style.top=e+"px":d.style.top=c+st+"px",window["ct"+b]=window.setTimeout("MyMove.Move_e('"+b+"', "+f+" , "+e+", "+(a+u)+", "+(c+st)+","+g+")",1))}}}
function wpa_count(){var b=document.getElementsByTagName("body").item(0),f=document.createElement("img");f.src="http://"+wpadomain+".qq.com/cgi/wpac?kfguin="+kfguin+"&ext=0&time="+(new Date).getTime()+"ip=172.23.30.15&";f.style.display="none";b.appendChild(f)}
$(function(b){if(b("#flash_sale").length)return!1;1==b.getCookie("show_set_name_tip")&&b.ajax({type:"POST",url:"index.php?app=default&act=showSetNickname",data:"user_name="+b.getCookie("uname"),dataType:"html",success:function(f){var e=location.hostname,e=e.slice(e.indexOf("."));b.setCookie("show_set_name_tip",0,null,"/",e);b("body").append(f)}})});
(function(b){"function"==typeof define&&define.amd?define(["jquery"],b):"object"==typeof exports?b(require("jquery")):b(jQuery)})(function(b){var f={wheelSpeed:10,wheelPropagation:!1,minScrollbarLength:null,maxScrollbarLength:null,useBothWheelAxes:!1,useKeyboard:!0,suppressScrollX:!1,suppressScrollY:!1,scrollXMarginOffset:0,scrollYMarginOffset:0,includePadding:!1},e=function(){var a=0;return function(){var b=a;return a+=1,".perfect-scrollbar-"+b}}();b.fn.perfectScrollbar=function(a,c){return this.each(function(){var g=
b.extend(!0,{},f),d=b(this);if("object"==typeof a?b.extend(!0,g,a):c=a,"update"===c)return d.data("perfect-scrollbar-update")&&d.data("perfect-scrollbar-update")(),d;if("destroy"===c)return d.data("perfect-scrollbar-destroy")&&d.data("perfect-scrollbar-destroy")(),d;if(d.data("perfect-scrollbar"))return d.data("perfect-scrollbar");d.addClass("ps-container");var u,q,h,m,k,v,p,n,l,r,s=b("<div class='ps-scrollbar-x-rail'></div>").appendTo(d),w=b("<div class='ps-scrollbar-y-rail'></div>").appendTo(d),
x=b("<div class='ps-scrollbar-x'></div>").appendTo(s),y=b("<div class='ps-scrollbar-y'></div>").appendTo(w),A=parseInt(s.css("bottom"),10),B=A===A,F=B?null:parseInt(s.css("top"),10),z=parseInt(w.css("right"),10),C=z===z,D=C?null:parseInt(w.css("left"),10),G="rtl"===d.css("direction"),t=e(),K=parseInt(s.css("borderLeftWidth"),10)+parseInt(s.css("borderRightWidth"),10),L=parseInt(s.css("borderTopWidth"),10)+parseInt(s.css("borderBottomWidth"),10),H=function(a){return g.minScrollbarLength&&(a=Math.max(a,
g.minScrollbarLength)),g.maxScrollbarLength&&(a=Math.min(a,g.maxScrollbarLength)),a},I=function(){var a={width:h,display:u?"inherit":"none"};a.left=G?d.scrollLeft()+h-k:d.scrollLeft();B?a.bottom=A-d.scrollTop():a.top=F+d.scrollTop();s.css(a);a={top:d.scrollTop(),height:m,display:q?"inherit":"none"};C?a.right=G?k-d.scrollLeft()-z-y.outerWidth():z-d.scrollLeft():a.left=G?d.scrollLeft()+2*h-k-D-y.outerWidth():D+d.scrollLeft();w.css(a);x.css({left:n,width:p-K});y.css({top:r,height:l-L});u?d.addClass("ps-active-x"):
d.removeClass("ps-active-x");q?d.addClass("ps-active-y"):d.removeClass("ps-active-y")},E=function(){h=g.includePadding?d.innerWidth():d.width();m=g.includePadding?d.innerHeight():d.height();k=d.prop("scrollWidth");v=d.prop("scrollHeight");!g.suppressScrollX&&k>h+g.scrollXMarginOffset?(u=!0,p=H(parseInt(h*h/k,10)),n=parseInt(d.scrollLeft()*(h-p)/(k-h),10)):(u=!1,p=0,n=0,d.scrollLeft(0));!g.suppressScrollY&&v>m+g.scrollYMarginOffset?(q=!0,l=H(parseInt(m*m/v,10)),r=parseInt(d.scrollTop()*(m-l)/(v-m),
10)):(q=!1,l=0,r=0,d.scrollTop(0));r>=m-l&&(r=m-l);n>=h-p&&(n=h-p);I()},M=function(){var a,c;x.bind("mousedown"+t,function(b){c=b.pageX;a=x.position().left;s.addClass("in-scrolling");b.stopPropagation();b.preventDefault()});b(document).bind("mousemove"+t,function(b){if(s.hasClass("in-scrolling")){var g=a+(b.pageX-c),e=h-p;n=0>g?0:g>e?e:g;g=parseInt(n*(k-h)/(h-p),10);d.scrollLeft(g);C?w.css({right:z-g}):w.css({left:D+g});b.stopPropagation();b.preventDefault()}});b(document).bind("mouseup"+t,function(){s.hasClass("in-scrolling")&&
s.removeClass("in-scrolling")});a=c=null},N=function(){var a,c;y.bind("mousedown"+t,function(b){c=b.pageY;a=y.position().top;w.addClass("in-scrolling");b.stopPropagation();b.preventDefault()});b(document).bind("mousemove"+t,function(b){if(w.hasClass("in-scrolling")){var g=a+(b.pageY-c),e=m-l;r=0>g?0:g>e?e:g;g=parseInt(r*(v-m)/(m-l),10);d.scrollTop(g);B?s.css({bottom:A-g}):s.css({top:F+g});b.stopPropagation();b.preventDefault()}});b(document).bind("mouseup"+t,function(){w.hasClass("in-scrolling")&&
w.removeClass("in-scrolling")});a=c=null},J=function(a,b){var c=d.scrollTop();if(0===a){if(!q)return!1;if(0===c&&0<b||c>=v-m&&0>b)return!g.wheelPropagation}c=d.scrollLeft();if(0===b){if(!u)return!1;if(0===c&&0>a||c>=k-h&&0<a)return!g.wheelPropagation}return!0},O=function(){g.wheelSpeed/=10;var a=!1;d.bind("mousewheel"+t,function(b,c,e,f){c=b.deltaX*b.deltaFactor||e;f=b.deltaY*b.deltaFactor||f;a=!1;g.useBothWheelAxes?q&&!u?(f?d.scrollTop(d.scrollTop()-f*g.wheelSpeed):d.scrollTop(d.scrollTop()+c*g.wheelSpeed),
a=!0):u&&!q&&(c?d.scrollLeft(d.scrollLeft()+c*g.wheelSpeed):d.scrollLeft(d.scrollLeft()-f*g.wheelSpeed),a=!0):(d.scrollTop(d.scrollTop()-f*g.wheelSpeed),d.scrollLeft(d.scrollLeft()+c*g.wheelSpeed));E();(a=a||J(c,f))&&(b.stopPropagation(),b.preventDefault())});d.bind("MozMousePixelScroll"+t,function(b){a&&b.preventDefault()})},P=function(){var a=!1;d.bind("mouseenter"+t,function(){a=!0});d.bind("mouseleave"+t,function(){a=!1});b(document).bind("keydown"+t,function(c){if(!(c.isDefaultPrevented&&c.isDefaultPrevented()||
!a||b(document.activeElement).is(":input,[contenteditable]"))){var g=0,e=0;switch(c.which){case 37:g=-30;break;case 38:e=30;break;case 39:g=30;break;case 40:e=-30;break;case 33:e=90;break;case 32:case 34:e=-90;break;case 35:e=-m;break;case 36:e=m;break;default:return}d.scrollTop(d.scrollTop()-e);d.scrollLeft(d.scrollLeft()+g);J(g,e)&&c.preventDefault()}})},Q=function(){var a=function(a){a.stopPropagation()};y.bind("click"+t,a);w.bind("click"+t,function(a){var b=parseInt(l/2,10);a=(a.pageY-w.offset().top-
b)/(m-l);0>a?a=0:1<a&&(a=1);d.scrollTop((v-m)*a)});x.bind("click"+t,a);s.bind("click"+t,function(a){var b=parseInt(p/2,10);a=(a.pageX-s.offset().left-b)/(h-p);0>a?a=0:1<a&&(a=1);d.scrollLeft((k-h)*a)})},R=function(){var a=function(a,b){d.scrollTop(d.scrollTop()-b);d.scrollLeft(d.scrollLeft()-a);E()},c={},g=0,e,f,h=null,k=!1;b(window).bind("touchstart"+t,function(){k=!0});b(window).bind("touchend"+t,function(){k=!1});d.bind("touchstart"+t,function(a){var b=a.originalEvent.targetTouches[0];c.pageX=
b.pageX;c.pageY=b.pageY;g=(new Date).getTime();null!==h&&clearInterval(h);a.stopPropagation()});d.bind("touchmove"+t,function(b){if(!k&&1===b.originalEvent.targetTouches.length){var d=b.originalEvent.targetTouches[0],h={};h.pageX=d.pageX;h.pageY=d.pageY;var d=h.pageX-c.pageX,m=h.pageY-c.pageY;a(d,m);c=h;var h=(new Date).getTime(),q=h-g;0<q&&(e=d/q,f=m/q,g=h);b.preventDefault()}});d.bind("touchend"+t,function(){clearInterval(h);h=setInterval(function(){return.01>Math.abs(e)&&.01>Math.abs(f)?(clearInterval(h),
void 0):(a(30*e,30*f),e*=.8,f*=.8,void 0)},10)})},S=function(){d.bind("scroll"+t,function(){E()})},T=function(){d.unbind(t);b(window).unbind(t);b(document).unbind(t);d.data("perfect-scrollbar",null);d.data("perfect-scrollbar-update",null);d.data("perfect-scrollbar-destroy",null);x.remove();y.remove();s.remove();w.remove();s=w=x=y=u=q=h=m=k=v=p=n=A=B=F=l=r=z=C=D=G=t=null},U=function(a){d.addClass("ie").addClass("ie"+a);var c=function(){I=function(){var a={left:n+d.scrollLeft(),width:p};B?a.bottom=
A:a.top=F;x.css(a);a={top:r+d.scrollTop(),height:l};C?a.right=z:a.left=D;y.css(a);x.hide().show();y.hide().show()}};6===a&&(function(){var a=function(){b(this).addClass("hover")},c=function(){b(this).removeClass("hover")};d.bind("mouseenter"+t,a).bind("mouseleave"+t,c);s.bind("mouseenter"+t,a).bind("mouseleave"+t,c);w.bind("mouseenter"+t,a).bind("mouseleave"+t,c);x.bind("mouseenter"+t,a).bind("mouseleave"+t,c);y.bind("mouseenter"+t,a).bind("mouseleave"+t,c)}(),c())},V="ontouchstart"in window||window.DocumentTouch&&
document instanceof window.DocumentTouch;return function(){var a=navigator.userAgent.toLowerCase().match(/(msie) ([\w.]+)/);a&&"msie"===a[1]&&U(parseInt(a[2],10));E();S();M();N();Q();V&&R();d.mousewheel&&O();g.useKeyboard&&P();d.data("perfect-scrollbar",d);d.data("perfect-scrollbar-update",E);d.data("perfect-scrollbar-destroy",T)}(),d})}});
(function(b){"function"==typeof define&&define.amd?define(["jquery"],b):"object"==typeof exports?module.exports=b:b(jQuery)})(function(b){function f(g){var d=g||window.event,f=u.call(arguments,1),q=0,n=0,l=0,r=0;if(g=b.event.fix(d),g.type="mousewheel","detail"in d&&(l=-1*d.detail),"wheelDelta"in d&&(l=d.wheelDelta),"wheelDeltaY"in d&&(l=d.wheelDeltaY),"wheelDeltaX"in d&&(n=-1*d.wheelDeltaX),"axis"in d&&d.axis===d.HORIZONTAL_AXIS&&(n=-1*l,l=0),q=0===l?n:l,"deltaY"in d&&(l=-1*d.deltaY,q=l),"deltaX"in
d&&(n=d.deltaX,0===l&&(q=-1*n)),0!==l||0!==n){if(1===d.deltaMode)var s=b.data(this,"mousewheel-line-height"),q=q*s,l=l*s,n=n*s;else 2===d.deltaMode&&(s=b.data(this,"mousewheel-page-height"),q*=s,l*=s,n*=s);return r=Math.max(Math.abs(l),Math.abs(n)),(!c||c>r)&&(c=r,h.settings.adjustOldDeltas&&"mousewheel"===d.type&&0===r%120&&(c/=40)),h.settings.adjustOldDeltas&&"mousewheel"===d.type&&0===r%120&&(q/=40,n/=40,l/=40),q=Math[1<=q?"floor":"ceil"](q/c),n=Math[1<=n?"floor":"ceil"](n/c),l=Math[1<=l?"floor":
"ceil"](l/c),g.deltaX=n,g.deltaY=l,g.deltaFactor=c,g.deltaMode=0,f.unshift(g,q,n,l),a&&clearTimeout(a),a=setTimeout(e,200),(b.event.dispatch||b.event.handle).apply(this,f)}}function e(){c=null}var a,c,g=["wheel","mousewheel","DOMMouseScroll","MozMousePixelScroll"],d="onwheel"in document||9<=document.documentMode?["wheel"]:["mousewheel","DomMouseScroll","MozMousePixelScroll"],u=Array.prototype.slice;if(b.event.fixHooks)for(var q=g.length;q;)b.event.fixHooks[g[--q]]=b.event.mouseHooks;var h=b.event.special.mousewheel=
{version:"3.1.9",setup:function(){if(this.addEventListener)for(var a=d.length;a;)this.addEventListener(d[--a],f,!1);else this.onmousewheel=f;b.data(this,"mousewheel-line-height",h.getLineHeight(this));b.data(this,"mousewheel-page-height",h.getPageHeight(this))},teardown:function(){if(this.removeEventListener)for(var a=d.length;a;)this.removeEventListener(d[--a],f,!1);else this.onmousewheel=null},getLineHeight:function(a){return parseInt(b(a)["offsetParent"in b.fn?"offsetParent":"parent"]().css("fontSize"),
10)},getPageHeight:function(a){return b(a).height()},settings:{adjustOldDeltas:!0}};b.fn.extend({mousewheel:function(a){return a?this.bind("mousewheel",a):this.trigger("mousewheel")},unmousewheel:function(a){return this.unbind("mousewheel",a)}})});
(function(b){function f(e,a){function c(a){a.stopPropagation();b("body").addClass("noSelect");var c=parseInt(n.obj.css(r),10);f=l?a.pageX:a.pageY;q="auto"==c?0:c;x?(document.ontouchmove=function(a){a.preventDefault();g(a.touches[0])},document.ontouchend=d):(b(document).bind("mousemove",g),b(document).bind("mouseup",d),n.obj.bind("mouseup",d))}function g(b){1>k.ratio&&(h=a.invertscroll&&x?Math.min(p[a.axis]-n[a.axis],Math.max(0,q+(f-(l?b.pageX:b.pageY)))):Math.min(p[a.axis]-n[a.axis],Math.max(0,q+
((l?b.pageX:b.pageY)-f))),w=h*v.ratio,k.obj.css(r,-w),n.obj.css(r,h))}function d(){b("body").removeClass("noSelect");b(document).unbind("mousemove",g);b(document).unbind("mouseup",d);b(document).unbind("click",d);n.obj.unbind("mouseup",d);document.ontouchmove=document.ontouchend=null}var f,q,h,m={obj:b(".viewport",e)},k={obj:b(".overview",e)},v={obj:b(".scrollbar",e)},p={obj:b(".track",v.obj)},n={obj:b(".thumb",v.obj)},l="x"===a.axis,r=l?"left":"top",s=l?"Width":"Height",w=0;h=q=0;f=void 0;var x=
"ontouchstart"in document.documentElement;this.update=function(b){m[a.axis]=m.obj[0]["offset"+s];k[a.axis]=k.obj[0]["scroll"+s];k.ratio=m[a.axis]/k[a.axis];v.obj.toggleClass("disable",1<=k.ratio);p[a.axis]="auto"===a.size?m[a.axis]:a.size;n[a.axis]=Math.min(p[a.axis],Math.max(0,"auto"===a.sizethumb?p[a.axis]*k.ratio:a.sizethumb));v.ratio="auto"===a.sizethumb?k[a.axis]/p[a.axis]:(k[a.axis]-m[a.axis])/(p[a.axis]-n[a.axis]);w="relative"===b&&1>=k.ratio?Math.min(k[a.axis]-m[a.axis],Math.max(0,w)):0;w=
"bottom"===b&&1>=k.ratio?k[a.axis]-m[a.axis]:isNaN(parseInt(b,10))?w:parseInt(b,10);b=s.toLowerCase();n.obj.css(r,w/v.ratio);k.obj.css(r,-w);f=n.obj.offset()[r];v.obj.css(b,p[a.axis]);p.obj.css(b,p[a.axis]);n.obj.css(b,n[a.axis])};this.update();(function(){x?m.obj[0].ontouchstart=function(a){1===a.touches.length&&(c(a.touches[0]),a.stopPropagation())}:(n.obj.bind("mousedown",c),p.obj.bind("mouseup",g))})();return this}b.tiny=b.tiny||{};b.tiny.scrollbar={options:{axis:"y",scroll:!0,lockscroll:!0,size:"auto",
sizethumb:"auto",invertscroll:!1}};b.fn.tinyscrollbar=function(e){var a=b.extend({},b.tiny.scrollbar.options,e);this.each(function(){b(this).data("tsb",new f(b(this),a))});return this};b.fn.tinyscrollbar_update=function(e){return b(this).data("tsb").update(e)}})(jQuery);
(function(b){function f(a){a=a.replace(/left|top/g,"0px");a=a.replace(/right|bottom/g,"100%");a=a.replace(/([0-9\.]+)(\s|\)|$)/g,"$1px$2");a=a.match(/(-?[0-9\.]+)(px|\%|em|pt)\s(-?[0-9\.]+)(px|\%|em|pt)/);return[parseFloat(a[1],10),a[2],parseFloat(a[3],10),a[4]]}if(!document.defaultView||!document.defaultView.getComputedStyle){var e=jQuery.css;jQuery.css=function(a,b,d){"background-position"===b&&(b="backgroundPosition");if("backgroundPosition"!==b||!a.currentStyle||a.currentStyle[b])return e.apply(this,
arguments);var f=a.style;return!d&&f&&f[b]?f[b]:e(a,"backgroundPositionX",d)+" "+e(a,"backgroundPositionY",d)}}var a=b.fn.animate;b.fn.animate=function(b){"background-position"in b&&(b.backgroundPosition=b["background-position"],delete b["background-position"]);"backgroundPosition"in b&&(b.backgroundPosition="("+b.backgroundPosition+")");return a.apply(this,arguments)};b.fx.step.backgroundPosition=function(a){if(!a.bgPosReady){var g=b.css(a.elem,"backgroundPosition");g||(g="0px 0px");g=f(g);a.start=
[g[0],g[2]];g=f(a.end);a.end=[g[0],g[2]];a.unit=[g[1],g[3]];a.bgPosReady=!0}g=[];g[0]=(a.end[0]-a.start[0])*a.pos+a.start[0]+a.unit[0];g[1]=(a.end[1]-a.start[1])*a.pos+a.start[1]+a.unit[1];a.elem.style.backgroundPosition=g[0]+" "+g[1]}})(jQuery);
(function(b){var f={J_set:b(".J_set"),init:function(){this.clickEvent()},clickEvent:function(){var a=this,c=navigator.appVersion.split(";"),g="",d=200;b("#J_unfold").mouseleave(function(){d=200});b(".J_pic_turn").mouseenter(function(e){var f=this,h=b(f).index();g=setTimeout(function(){d=0;b("#J_unfold").addClass("hover-"+(h+1));b(f).css({width:"707px"}).addClass("hover");1<c.length?10>parseInt(c[1].replace(/[ ]/g,"").replace(/MSIE/g,""))?a.addAnimation(h):b("#J_unfold").addClass("hover-fie"+(h+1)):
b("#J_unfold").addClass("hover-fie"+(h+1))},d);delayLazy("_h"+h)}).mouseleave(function(){var d=this,e=b(d).index();setTimeout(function(){b("#J_unfold").removeClass("hover-"+(e+1));b(d).css({width:"195px"}).removeClass("hover");1<c.length?10>parseInt(c[1].replace(/[ ]/g,"").replace(/MSIE/g,""))?a.removeAnimation(e):b("#J_unfold").removeClass("hover-fie"+(e+1)):b("#J_unfold").removeClass("hover-fie"+(e+1))},0);clearTimeout(g)})},addAnimation:function(a){function c(a){var c=0,d=600+60*a;b.each(g,function(g,
e){g>a?(b(this).stop().animate({left:d},300),d+=60):(b(this).stop().animate({left:c},300),c+=60)})}var g=b(".J_pic_turn");if(0==a){var d=600;b.each(g,function(a,c){0!=a&&(b(this).stop().animate({left:d},300),d+=66)})}else 1==a||2==a||3==a?c(a):4==a&&(d=0,b.each(g,function(a,c){b(this).stop().animate({left:d},300);d+=66}))},removeAnimation:function(a){a=b(".J_pic_turn");var c=0;b.each(a,function(a,d){b(this).stop().animate({left:c},300);c+=195})}},e={J_cc_level:b(".J_cc_level"),J_dynamic:b("#J_dynamic"),
out_t:"",dynamic_index:0,dynamic_all:0,J_bigerimg:b(".J_bigerimg"),init:function(){this.eventBind();this.tickling();this.showAllMenu();this.MarketTheme();this.fixedHead();this.loginStatus();var a=b("#J_main_pic2 li").length;this.rollInit("#J_main_pic","J_main_pic-n",3E3,300);1<a&&this.rollInit("#J_main_pic2","J_main_pic-n",5E3,200);this.purchaseAjax();this.dynamicAjax()},eventBind:function(){var a=this;b("#J_intro").find("li").mouseover(function(){var a=b(this);a.addClass("active").siblings().removeClass("active");
b("#J_intro_cont").find(".J_intro_tag").eq(a.index()).show().siblings().hide();b(window).trigger("scroll")});b("#J_nav_tag").mouseover(function(){b(this).addClass("active")}).mouseout(function(){b(this).removeClass("active")});a.J_dynamic.hover(function(){clearTimeout(a.out_t)},function(){a.dynamic_index>a.dynamic_all&&(a.dynamic_index=0);a.dynamicTurn(a.dynamic_index)});var c=navigator.appVersion.split(";");1<c.length&&(9<parseInt(c[1].replace(/[ ]/g,"").replace(/MSIE/g,""))||/Trident\/7\./.test(navigator.userAgent))&&
b(".type-b li").addClass("margin-ie");b("#J_login_msg").on("click","#53KeFu",function(){1>b("#53KeFuForm").length&&(b(".53KeFu").append("<a id='53KeFuForm' href='tencent://message/?Menu=yes&amp;uin=800037035&amp;Service=58&amp;SigT=A7F6FEA02730C98896A1DEA483E2913FA3A1005974DB69645C18DB3B778FFEA69BFB6C2383F063981EE5264BA7E52B0E342DE51308776441F9E72F5FEC9B232F97198CB24FF3F16C5E7B7A7BE0C8CF5657FCB1D3DF60FF22ED02FE7D7860ADE5CC3638D473685D5265C05351BD3C4C47D54ACBB9C5450108&amp;SigU=30E5D5233A443AB2DCDF0343E2A95109CFC323AB179B7FAB961FB28629F6408DB8FD41E01E87FA1766AF3A13630EB7F4F6EFCFB7CBA8097A0760613E3169FA96A85E9D29EEA40856'></a>"),
""!=b.getCookie("uname")&&(b.ajax({type:"GET",url:"/index.php?app=default&act=ajaxGetKeFuUrl",async:!1,data:{part:1},dataType:"json",success:function(a){unique_id=a.unique_id}}),b("#53KeFuForm").attr("action",b("#53KeFuForm").attr("action")+"&unique_id="+unique_id)));b("#53KeFuForm")[0].click()})},tickling:function(){b("#J_feedback_logo").on("click",function(){b(this).bind("selectstart",function(){return!1});b(this).addClass("logo-hover");b(this).hasClass("active")?(b("#J_feedback_box").hide(),b(this).removeClass("active logo-hover")):
(b("#J_feedback_box").show(),b("#J_tip_one").show(),b(this).addClass("active"))});b(".feedback-top label,.feedback-middle label").on("click",function(){b(this).siblings("label").children(".checkbox-style").removeClass("checkbox-true");b(this).children(".checkbox-style").addClass("checkbox-true");b(this).siblings("label").children("input").attr("checked",!1);b(this).children("input").attr("checked",!0)});b("#J_feedback_click").click(function(){var a=b(".feedback-top .all-checkbox:checked").length,
c=b(".feedback-middle .all-checkbox:checked").length,g=b(".feedback-top .all-checkbox:checked").val(),d=b(".feedback-middle .all-checkbox:checked").val(),e=b("#J_feedback_textarea").val();a?b(".J_tishi_one").hide():b(".J_tishi_one").show();c?b(".J_tishi_two").hide():b(".J_tishi_two").show();if(a&&c&&e){var f=new Date,a=f.getTime()+6E4,c=b.getCookie("feedback_time");b.getCookie("feedback_time")&&a>c&&b.removeCookie("feedback_time");b.getCookie("feedback_time")?b("#J_text_numerr").text("\u63d0\u4ea4\u4e4b\u540e5\u5206\u949f\u518d\u63d0\u4ea4~").show():
b.ajax({url:"/index.php?app=default&act=feedback",data:{isconvenience:g,issatisfaction:d,content:e,from_page:document.location.href,type:17,jsonp:1},dataType:"jsonp",success:function(a){a=f.setTime(f.getTime()+3E5);b.setCookie("feedback_time",a,f,"/");b("#J_text_numerr").hide();b("#J_tip_one").hide();b("#J_tip_two").show();setTimeout(function(){b("#J_feedback_box").hide();b("#J_tip_two").hide();b("#J_feedback_logo").removeClass("active logo-hover")},1500);b(".all-checkbox").attr("checked",!1);b(".checkbox-style").removeClass("checkbox-true");
b("#J_feedback_textarea").val("")}})}else return b("#J_text_numerr").text("\u4eb2\uff01\u60a8\u7684\u95ee\u5377\u8fd8\u4e0d\u5b8c\u6574\u54e6~").show(),!1}).mousedown(function(){b(this).addClass("feedback-clickdown")}).mouseup(function(){b(this).removeClass("feedback-clickdown")});b("#J_m_num").text(500);b("#J_feedback_textarea").bind("keyup",function(){var a=b(this),c=a.val();500<c.length?a.val(c.substring(0,500)):b("#J_num").text(c.length)})},showAllMenu:function(){var a=b("#J_good_map"),c=b("#J_source_map"),
g=b("#J_type_sex"),d=g.find(".active").attr("data-sex");0==d?g.find(".active").attr("href",""+search_domain+"/s-category-289.html"):g.find(".active").attr("href",""+search_domain+"/s-category-292.html");a.mouseenter(function(){b(this).addClass("active");g.find("a").removeClass("active");c.stop().slideDown("fast")}).mouseleave(function(){g.find("a").eq(d).addClass("active");b(this).removeClass("active");c.stop().slideUp("fast")})},MarketTheme:function(){function a(a,g){a.hasClass("active")||(a.addClass("active").siblings(".J_cc_level").removeClass("active"),
b(".J_cc_style").show().stop().animate({width:g+"px"},300,function(){a.siblings(".J_cc_level").find(".J_cc_style").hide()}),a.siblings(".J_cc_level").find(".J_type_hide").animate({opacity:0},200,function(){b(this).hide();a.find(".J_type_hide").show().animate({opacity:1},200)}))}this.J_cc_level.mouseenter(function(){var c=b(this),g=c.find(".J_type").length,d=204;1<g&&(d=3<=g?630:204*g);a(c,d)}).mouseleave(function(){var c=b(".J_cc_level").eq(0);a(c,204)})},fixedHead:function(){function a(a){var b=
"",b=a?'<img src="'+STATIC_URL+'/themes/mall/default/home/v6/images/logo.png" alt="\u8863\u8054\u7f51">':h;c.find(".logo-link").html(b)}var c=b("#ely-hd"),g=c.height()+b("#sitenav").height()+b("#top-banner").height()+30,d=b(document);b(window).height();var e=b("<div/>").css({height:c.outerHeight(),"z-index":114,position:"relative"}),f=null,h=c.find(".logo-link").html();c.wrap(e);b(window).bind("scroll",function(){clearTimeout(f);f=setTimeout(function(){d.scrollTop()>g?(c.addClass("hd-fixed").stop(!0,
!1).animate({marginTop:0}),a(!0)):(c.removeClass("hd-fixed").css("marginTop",""),a(!1))},50)})},rollInit:function(a,c,g,d,e){var f=b(a);if(!f.length||!f.find("li").length)return!1;var h=f.find("ul").children().length,m=[],k="<div class='sqr-nav'><div class='"+c+" pr none'></div>",v=null;if(e){var p=f.find("li").length,n=f.find(".nv-info");f.find(".nv-prv").addClass("pr");f.find(".nv-nex").addClass("ne");n.html("1/"+p)}else{for(var l=0;l<h;l++)m.push("."+c+"."+(l+1)),k+="<div class='"+c+" "+(l+1)+
"'></div>";v=b(k+("<div class='"+c+" ne none'></div></div>")).css("marginLeft",12*-h);v.children().eq(1).addClass("active");f.append(v)}f.jCarouselLite({btnNext:a+" .nv-nex",btnPrev:a+" .nv-prv",btnGo:m,scroll:1,visible:1,auto:g,mousehover:!0,speed:d,beforeStart:function(a){a=b(a).index();delayLazy("_t"+a);changeLazy(f)},afterEnd:function(a){a=b(a);var c=a.index(),d=a.siblings().length;c==d&&(c=1);0==c&&(c=d-1);e?n.html(c+"/"+p):(a.addClass("active").siblings().removeClass("active"),v.children().removeClass("active").eq(c).addClass("active"))}})},
loginStatus:function(){var a=new Date,c="",c=5<a.getHours()&&12>a.getHours()?"\u4e0a\u5348\u597d\uff0c\u6b22\u8fce\u6765\u5230\u8863\u8054":11<a.getHours()&&18>a.getHours()?"\u4e0b\u5348\u597d\uff0c\u6b22\u8fce\u6765\u5230\u8863\u8054":"\u665a\u4e0a\u597d\uff0c\u6b22\u8fce\u6765\u5230\u8863\u8054";b.ajax({type:"get",url:"/index.php?app=default&act=ajaxGetOrderNum",dataType:"json",success:function(a){var d="";"0"==a.retval.user_id?d+='<p>\u6b22\u8fce\u6765\u5230\u8863\u8054\u7f51<span class="limimg login-logo"></span></p>\r\n                                <ul class="clearfix">\r\n                                    <li><a href="/index.php?app=member&act=login"><span class="limimg login-bt"></span>\u767b\u5f55</a></li>\r\n                                    <li><a href="/index.php?app=member&act=register"><span class="limimg register-bt"></span>\u6ce8\u518c</a></li>\r\n                                    <li><a href="javascript:void(0);" id="53KeFu"><span class="limimg enter-bt"></span>\u5165\u9a7b</a></li>\r\n                                </ul>':
(d+='<div class="login-header clearfix">\r\n                                <span id="J_login_msg_pic" class="login-pic">\r\n                                    <img src="'+a.retval.userUrl+'" title="'+a.retval.name+'" />\r\n                                </span>\r\n                                <div class="login-desr">\r\n                                    <p class="login-name">HI,'+a.retval.name+'</p>\r\n                                    <p class="login-text">'+c+"</p>\r\n                                </div>\r\n                            </div>",
d=a.retval.userData.isStore&&15!=a.retval.userData.isPromise?a.retval.userData.taskFulfilling?d+('<div class="login-after-statu">\r\n                                            <div class="login-statu-num clearfix">\r\n                                                <span>'+a.retval.pending+"</span>\r\n                                                <span>"+a.retval.accepted+"</span>\r\n                                                <span>"+a.retval.shipped+"</span>\r\n                                                <span>"+
a.retval.backing+'</span>\r\n                                            </div>\r\n                                            <div class="login-statu-name clearfix">\r\n                                                <a rel="nofollow" href="'+SITE_URL+'/index.php?app=sellerorder&type=pending" target="_blank">\u5f85\u4ed8\u6b3e</a>\r\n                                                <a rel="nofollow" href="'+SITE_URL+'/index.php?app=sellerorder&type=accepted" target="_blank">\u5f85\u53d1\u8d27</a>\r\n                                                <a rel="nofollow" href="'+
SITE_URL+'/index.php?app=sellerorder&type=shipped" target="_blank">\u5f85\u6536\u8d27</a>\r\n                                                <a rel="nofollow" href="'+SITE_URL+'/index.php?app=sellerorder&type=evalua" target="_blank">\u9000\u8d27/\u9000\u6b3e</a>\r\n                                            </div>\r\n                                        </div>'):d+('<div class="login-statu-store clearfix">\r\n                                            <a rel="nofollow" href="'+SITE_URL+'/index.php?app=goods&act=addGoodsIndex" target="_blank">\u4e0a\u4f20\u5546\u54c1</a>\r\n                                            <a rel="nofollow" href="'+
SITE_URL+'/index.php?app=my_store&act=settings" target="_blank">\u5e97\u94fa\u8bbe\u7f6e</a>\r\n                                            <a class="last" rel="nofollow" href="'+SITE_URL+'/index.php?app=market_vendor" target="_blank">\u5b9e\u4f53\u8ba4\u8bc1</a>\r\n                                        </div>'):d+('<div class="login-after-statu">\r\n                                        <div class="login-statu-num clearfix">\r\n                                            <span>'+a.retval.pending+
"</span>\r\n                                            <span>"+a.retval.accepted+"</span>\r\n                                            <span>"+a.retval.shipped+"</span>\r\n                                            <span>"+a.retval.evalua+'</span>\r\n                                        </div>\r\n                                        <div class="login-statu-name clearfix">\r\n                                            <a rel="nofollow" href="'+SITE_URL+'/index.php?app=buyerorder&type=pending" target="_blank">\u5f85\u4ed8\u6b3e</a>\r\n                                            <a rel="nofollow" href="'+
SITE_URL+'/index.php?app=buyerorder&type=accepted" target="_blank">\u5f85\u53d1\u8d27</a>\r\n                                            <a rel="nofollow" href="'+SITE_URL+'/index.php?app=buyerorder&type=shipped" target="_blank">\u5f85\u6536\u8d27</a>\r\n                                            <a rel="nofollow" href="'+SITE_URL+'/index.php?app=buyerorder&type=evalua" target="_blank">\u5f85\u8bc4\u4ef7</a>\r\n                                        </div>\r\n                                    </div>'));
b("#J_login_msg").append(d)}})},purchaseAjax:function(){var a=this;b.ajax({url:"/index.php?app=default&act=ajaxGetSellerNum",type:"GET",dataType:"json",success:function(b){a.showNum(b.retval.num);setTimeout(function(){a.purchaseAjax()},18E5)},error:function(){}})},showNum:function(a){for(var c=b("#J_purchase i"),e=String(a).length,d=0;d<e;d++){c.length<=d&&b("#J_purchase").append("<i></i>");var f=String(a).charAt(d),f=36*-parseInt(f);b("#J_purchase i").eq(d).animate({backgroundPosition:"(0 "+String(f)+
"px)"},"slow","swing")}},dynamicAjax:function(){var a=this;b.ajax({url:"/index.php?app=default&act=ajaxForm",type:"GET",dataType:"json",success:function(b){a.dynamic_all=b.retval.length;1==b.done&&a.dynamicHtml(b);setTimeout(function(){a.dynamicAjax()},9E5)},error:function(){}})},dynamicHtml:function(a){var c=this,e="",d="",f="";b.each(a.retval,function(a,b){f=0==a?"mg-top-tr":"";e+='<li class="'+f+' J_home_goods" store-id="'+b.store_id+'">\r\n                            <a class="pic" href="'+b.storeLink+
'" target="_blank"><img src="'+b.goodsImage+'"></a>\r\n                            <div class="sell-message">\r\n                                <a href="'+b.storeLink+'" title="'+b.storeName+'" target="_blank"><p class="name">'+b.storeName+"</p></a>\r\n                                <p>"+b.message+"</p>\r\n                                <p>"+b.time+"</p>\r\n                            </div>\r\n                        </li>";3>a&&(d+='<li class="J_home_goods" store-id="'+b.store_id+'">\r\n                                    <a class="pic" href="'+
b.storeLink+'" target="_blank"><img src="'+b.goodsImage+'"></a>\r\n                                    <div class="sell-message">\r\n                                        <a href="'+b.storeLink+'" title="'+b.storeName+'" target="_blank"><p class="name">'+b.storeName+"</p></a>\r\n                                        <p>"+b.message+"</p>\r\n                                        <p>"+b.time+"</p>\r\n                                    </div>\r\n                                </li>")});e+=d;c.J_dynamic.html(e);
setTimeout(function(){c.dynamicTurn(0)},3E3)},dynamicTurn:function(a){function c(){a==e.dynamic_all&&(a=0,d=b(".mg-top-tr").height(),b(".mg-top-tr").css({marginTop:"15px"}));b(".mg-top-tr").animate({marginTop:-d});d+=90;e.dynamic_index=a;a++;e.out_t=setTimeout(function(){c()},3E3)}var e=this,d=0==a?b(".mg-top-tr").height():b(".mg-top-tr").height()+90*a;clearTimeout(e.out_t);c()}};b(function(){f.init();e.init();changeLazy();b.imglazy({childContainer:".isnone"});b("#J_consult").on("click",function(){b.ajax({url:SITE_URL+
"/index.php?app=default&act=update_consultation_num",type:"post"})})});b(function(){var a=[],c=b(".J_ranklist").children("li"),e;Allrecord.theVisual(".J_home_goods",a);b(window).scroll(function(){clearTimeout(e);e=setTimeout(function(){Allrecord.theVisual(".J_home_goods",a)},150)});c.on("mouseenter",function(){Allrecord.theVisual(".J_home_goods",a)});Allrecord.recordTrack("goods_eelly_home_page",a)})})(jQuery);
(function(b){function f(b){var a=["webkit","Moz","ms","o"],c,f=[],d=document.documentElement.style,u=function(a){return a.replace(/-(\w)/g,function(a,b){return b.toUpperCase()})};for(c in a)f.push(u(a[c]+"-"+b));f.push(u(b));for(c in f)if(f[c]in d)return!0;return!1}window.v6obj={J_recomgoods:b(".J_recomgoods"),category:b("#category"),recommend:b("#recommend"),init:function(){this.categoStor();this.rankbox();this.Pfmaket();this.Recom();this.RemAjax();this.Actseinit();this.errorPic()},errorPic:function(){this.recommend.find("img").on("error",
function(){b(this).attr("src",STATIC_URL+"/data/system/default_goods_image.gif")});this.category.find("img").on("error",function(){b(this).attr("src",STATIC_URL+"/data/system/default_goods_image.gif")})},Actseinit:function(){var e=f("flex-grow"),a=b(".J_actse li"),c=100/a.length-1;e||a.css({width:c+"%","float":"left"})},categoStor:function(){b(".J_storelist").children("li").on({mouseenter:function(){var e=b(this),a=e.find(".J_listimg"),c=e.find(".J_listinf"),g=c.children(".J_listinfori"),d=f("transform");
e.addClass("active").siblings().removeClass("active");a.addClass("active");c.addClass("active");g.addClass("active").prev().addClass("none");d||(c.stop().animate({width:"266px"},100),a.stop().animate({width:"80px"},100),e.find(".list-imgs").stop().animate({width:"110px"},100),e.find(".list-infors").stop().animate({width:"270px"},100))},mouseleave:function(){var e=b(this),a=e.find(".J_listimg"),c=e.find(".J_listinf"),g=c.children(".J_listinfori"),d=f("transform");e.removeClass("active");a.removeClass("active");
c.removeClass("active");g.removeClass("active").prev().removeClass("none");d||(c.stop().animate({width:"210px"},100),a.stop().animate({width:"148px"},100),e.find(".list-imgs").stop().animate({width:"148px"},100),e.find(".list-infors").stop().animate({width:"230px"},100))}})},rankbox:function(){b(".J_ranklist").children("li").on("mouseenter",function(e){e=b(this);var a=e.find(".J_rankimg"),c=e.find(".rank-num");e.addClass("active").siblings().removeClass("active");c.addClass("block");a.removeClass("none");
e.siblings().find(".J_rankimg").addClass("none");e.siblings().find(".rank-num").removeClass("block")})},loadPicBlur:function(){var e=b(".J_picViewImg"),a=b(".J_svgImg");"ActiveXObject"in window&&9<parseInt(b.browser.version)&&(b(".J_ieBlurHack").show().css("line-height","0"),e.on("mouseenter",function(){var c=b(this).show();a.attr({"xlink:href":c.attr("src"),height:c.height(),width:c.width()}).show()}))},Pfmaket:function(){b(".J_makcens>li").mouseenter(function(e){e=b(this);var a=f("transform");e.addClass("active").siblings().removeClass("active");
e.find(".J_makcenTop").addClass("active");a||e.find(".J_makcenTop").stop().animate({height:"115px"},100)}).mouseleave(function(e){e=b(this);var a=f("transform");e.removeClass("active");e.find(".J_makcenTop").removeClass("active");a||e.find(".J_makcenTop").animate({height:"67px"},100)})},Recom:function(){b(".J_recomgoods").on("mouseenter mouseleave",".J_recom li",function(e){e.preventDefault();var a=b(this),c=f("transform");"mouseenter"==e.type&&(a.addClass("active").siblings().removeClass("active"),
a.find(".J_imgover").addClass("active").siblings("img").addClass("filter"),a.find(".J_bale").addClass("none").siblings().removeClass("none"),a.find(".J_cover").addClass("active"),c||(a.find(".J_cover").css({background:"#000",filter:"alpha(opacity=30)"}),a.find(".J_cover").css("display","block"),a.find(".J_imgover").css("display","block"),a.find(".J_imgover").stop().animate({top:"0"},300)));"mouseleave"==e.type&&(a.removeClass("active"),a.find(".J_imgover").removeClass("active").siblings("img").removeClass("filter"),
a.find(".J_bale").removeClass("none").siblings().addClass("none"),a.find(".J_cover").removeClass("active"),c||(a.find(".J_cover").css("display","none"),a.find(".J_imgover").css("display","none")))});b("#J_setting").click(function(e){b(this).siblings(".J_setbox").slideToggle(300)});b(".J_requer").click(function(){b(this).closest(".J_setbox").slideUp(300)});b(".J_setul").on("click","li",function(e){e.preventDefault();b(this).addClass("active").siblings().removeClass("active")})},RemAjax:function(){var e=
this,a=b(".J_recomgoods"),c=b(window),g,d=a.offset().top,u=1,q=f("transform");c.scroll(function(){g=c.scrollTop();g>d-1E3&&u&&(u=0,b.ajax({url:SITE_URL+"/index.php?app=default&act=ajaxHomePageRecommend",type:"GET",success:function(b){a.prepend(b);a.find("#J_loading").hide();e.errorPic();q||(b=a.find(".J_recom").children("li"),b.find(".J_cover").css("display","none"),b.find(".J_imgover").css("display","none"));changeLazy()},error:function(){html='<div class="no-data"><img src="'+STATIC_URL+'/themes/mall/default/home/v5/images/error_pic.png"></div>';
a.prepend(html);a.find("#J_loading").hide()}}))})}};v6obj.init()})(jQuery);
function lazyload(b){var f={defObj:$(document),defHeight:-400},f=$.extend(f,b||{}),e="object"==typeof f.defObj?f.defObj.find("img"):$(f.defObj).find("img"),a=function(){e.each(function(){if($(this).offset().top<=document.documentElement.clientHeight+Math.max(document.documentElement.scrollTop,document.body.scrollTop)-f.defHeight){var a=$(this).attr("lazy_src");a&&($(this).attr("src",a).removeAttr("lazy_src"),$(this).bind("error",function(){if(-1<$(this).attr("src").indexOf("amos.alicdn.com"))$(this).attr("src",
STATIC_URL+"/themes/store/default/styles/images/T1tm9.XdRnXXaHNz_X-16-16.gif");else if("goods_des"!=$(this).attr("pictype"))if($(this).attr("picsize")){var a=$(this).attr("picsize");$(this).attr("src",STATIC_URL+"/data/system/default_goods_image_"+a+".gif")}else $(this).attr("src",STATIC_URL+"/data/system/default_goods_image.gif");$(this).unbind("error")}).removeClass("J_lazyImg"))}})};a();$(window).bind("scroll",function(){a()})}$(document).ready(function(){lazyload()});
(function(b,f,e){e.extend({imglazy:function(a){var b={threshold:400,event:"scroll",container:window,childContainer:null,dataAttribute:"lazy",errorImg:STATIC_URL+"/data/system/default_goods_image.gif"};e.extend(b,a||{});var f=b.container==window?e(document):e(b.container),d=function(){var a=e(window).scrollTop()+e(window).height()+b.threshold,d=0<e(window).scrollTop()-b.threshold?e(window).scrollTop()-b.threshold:0;b.childContainer?f.find(b.childContainer).each(function(f,g){var k=e(g);k.offset().top>=
d&&k.offset().top<=a&&k.is(":visible")&&k.find("img[data-"+b.dataAttribute+"]").each(function(a,d){var f=e(d);f.attr("src",f.data(b.dataAttribute)).removeAttr("data-"+b.dataAttribute).error(function(){e(this).attr("src",b.errorImg)})})}):f.find("img[data-"+b.dataAttribute+"]").each(function(f,g){var k=e(g);k.offset().top>=d&&k.offset().top<=a&&k.is(":visible")&&k.attr("src",k.data(b.dataAttribute)).removeAttr("data-"+b.dataAttribute).error(function(){e(this).attr("src",b.errorImg)})})};d();e(b.container).on("scroll",
function(){setTimeout(function(){d()})})}})})(window,document,jQuery);
